version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  # Should be bigger than or equal to the total number of dependencies (currently 16)
  open-pull-requests-limit: 20
  target-branch: develop
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: develop
