version: '2'

services:
  aiida-optimade:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AIIDA_PATH: /app
      AIIDA_PROFILE: optimade
    volumes:
     - '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository-quicksetup:/app/.aiida/repository-optimade'
    ports:
      - '3253:80'
